version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: campusflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: campus_flow_password
      MYSQL_DATABASE: campusflow
      MYSQL_USER: campus_flow
      MYSQL_PASSWORD: campus_flow_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
